#ifndef PINS_H
#define PINS_H

// LIGHTING
#define LED_LIGHTING_HIGH PC7
#define LED_LIGHTING_MEDIUM PB15
#define LED_LIGHTING_LOW PB13

#define BUTTON_LIGHTING_HIGH PB3
#define BUTTON_LIGHTING_MEDIUM PA12
#define BUTTON_LIGHTING_LOW PA8
#define BUTTON_LIGHTING_OFF PC12


// RESTROOM
#define LED_RESTROOM1_RED PB14
#define LED_RESTROOM1_GREEN PB12
#define LED_RESTROOM2_GREEN PA0
#define LED_RESTROOM2_RED PA1

#define SENSOR_RESTROOM1 PC2
#define SENSOR_RESTROOM2 PC0


// CALL
#define BUTTON_CALL PB5
#define OUTPUT_CALL PB10
#define INPUT_CALL_RESET PA15


// SECURITY
#define BUTTON_SECURITY PC13
#define LED_SECURITY PC6
#define BUZZER_SECURITY PC5
#define INPUT_SECURITY PB9
#define OUTPUT_SECURITY PB1

// SPEAKERS
#define SPEAKER_I2C_SDA PB6
#define SPEAKER_I2C_SCL PB7

#define BUTTON_SPEAKER_MINUS PB4
#define BUTTON_SPEAKER_PLUS PC3
#define INPUT_SPEAKER_ALERT PC1

#define LED_SPEAKER_1 PC9
#define LED_SPEAKER_2 PA11
#define LED_SPEAKER_3 PA15
#define LED_SPEAKER_4 PC11
#define LED_SPEAKER_5 PD2

const uint8_t LEDS[5] = {LED_SPEAKER_1, LED_SPEAKER_2, LED_SPEAKER_3, LED_SPEAKER_4, LED_SPEAKER_5};

// CAN
#define CAN_CS PA4

#endif