#ifndef SETTINGS_H
#define SETTINGS_H

// SECURITY
#define SIREN_INTERVAL 100

// SPEAKER
#define SPEAKER_MAX_LEVEL 30
#define SPEAKER_MIN_LEVEL 0
#define SPEAKER_SAVER_TIME 5000

// CAN
#define CAN_SURVEY 3000
#define COMPARTMENT_ROOM 0x003

#endif